commit

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -219,6 +219,19 @@ jobs:
             exit 1
           fi
           
+          PUBLIC_URL_RESPONSE=$(curl -X POST https://slack.com/api/files.sharedPublicURL \
+            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
+            --data "file=$FILE_ID")
+          
+          PUBLIC_FILE_URL=$(echo "$PUBLIC_URL_RESPONSE" | jq -r '.file.permalink_public')
+          
+          if [ -z "$PUBLIC_FILE_URL" ]; then
+            echo "Error: Could not retrieve the public URL for the file."
+            exit 1
+          fi
+          
+          echo "Public URL for the file: $PUBLIC_FILE_URL"
+          
           # Step 4: Complete the file upload via Slack API
           COMPLETE_UPLOAD_RESPONSE=$(curl -X POST https://slack.com/api/files.completeUploadExternal \
           -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
@@ -264,7 +277,7 @@ jobs:
                 }
               }
             ]
-          }' "$CHANNEL_ID" "$FILE_URL")")
+          }' "$CHANNEL_ID" "$PUBLIC_FILE_URL")")
           
           echo "Notification Response: ${NOTIFY_RESPONSE}"
           
